export const tableData = [
  {
    name: 'John Brown',
    age: 18,
    address: 'New York No. 1 Lake Park',
    province: 'America',
    city: 'New York',
    zip: 100000,
    id: 1,
  },
  {
    name: 'Jim Green',
    age: 24,
    address: 'Washington, D.C. No. 1 Lake Park',
    province: 'America',
    city: 'Washington, D.C.',
    zip: 100000,
    id: 2,
  },
  {
    name: 'Joe Black',
    age: 30,
    address: 'Sydney No. 1 Lake Park',
    province: 'Australian',
    city: 'Sydney',
    zip: 100000,
    id: 3,
  },
  {
    name: 'Jon Snow',
    age: 26,
    address: 'Ottawa No. 2 Lake Park',
    province: 'Canada',
    city: 'Ottawa',
    zip: 100000,
    id: 4,
  },
];
